language: ruby
rvm:
  - 2.2.2
env:
  - RAILS_ENV=test
before_script:
  - "mysql -e 'create database rails_on_rails_test;'"
  - "cp ./.travis.database.yml ./config/database.yml"
cript:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
addons:
  code_climate:
    repo_token: 68a5e4105eac2482da1f2b5de3b9b8b90a16cbd08d346ac07176bbd8442c8220